from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Optional
from uuid import UUID, uuid4

from sqlalchemy import Column, Enum as SQLEnum, ForeignKey, JSON, UniqueConstraint, LargeBinary
from sqlmodel import Field, SQLModel


class MessageStatus(str, Enum):
    QUEUED = "queued"
    PROCESSING = "processing"
    READY = "ready"
    ERROR = "error"


class SenderType(str, Enum):
    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class User(SQLModel, table=True):
    """Application user with access and product scopes."""

    __tablename__ = "users"

    id: UUID = Field(default_factory=uuid4, primary_key=True, index=True)
    username: str = Field(max_length=128, unique=True, index=True)
    email: Optional[str] = Field(default=None, max_length=255, unique=True, index=True)
    full_name: Optional[str] = Field(default=None, max_length=255)
    password_hash: str = Field(max_length=255)
    roles: list[str] = Field(
        default_factory=list,
        sa_column=Column(JSON, nullable=False, server_default="[]"),
    )
    allowed_products: list[str] = Field(
        default_factory=list,
        sa_column=Column(JSON, nullable=False, server_default="[]"),
    )
    allowed_agents: list[str] = Field(
        default_factory=list,
        sa_column=Column(JSON, nullable=False, server_default="[]"),
    )
    token_version: int = Field(default=1)
    is_active: bool = Field(default=True)
    last_login_at: Optional[datetime] = Field(default=None, nullable=True)
    created_at: datetime = Field(default_factory=utcnow, nullable=False)
    updated_at: datetime = Field(default_factory=utcnow, nullable=False)


class Thread(SQLModel, table=True):
    """Chat thread owned by an end user."""

    __tablename__ = "threads"

    id: UUID = Field(default_factory=uuid4, primary_key=True, index=True)
    owner_id: str = Field(index=True, max_length=128)
    title: Optional[str] = Field(default=None, max_length=255)
    summary: Optional[str] = Field(default=None, title="Thread summary generated by LLM")
    attributes: dict = Field(
        default_factory=dict,
        sa_column=Column("metadata", JSON, nullable=False, server_default="{}"),
    )
    is_deleted: bool = Field(default=False, index=True)
    created_at: datetime = Field(default_factory=utcnow, nullable=False)
    updated_at: datetime = Field(default_factory=utcnow, nullable=False)
    deleted_at: Optional[datetime] = Field(default=None, nullable=True)


class Message(SQLModel, table=True):
    """Individual message exchanged inside a thread."""

    __tablename__ = "messages"

    id: UUID = Field(default_factory=uuid4, primary_key=True, index=True)
    thread_id: UUID = Field(
        foreign_key="threads.id",
        nullable=False,
        index=True,
    )
    sender_id: str = Field(max_length=128, nullable=False)
    sender_type: SenderType = Field(
        sa_column=Column(SQLEnum(SenderType, name="sender_type_enum", native_enum=False), nullable=False)
    )
    status: MessageStatus = Field(
        default=MessageStatus.QUEUED,
        sa_column=Column(
            SQLEnum(MessageStatus, name="message_status_enum", native_enum=False),
            nullable=False,
            default=MessageStatus.QUEUED,
        ),
    )
    text: str = Field(nullable=False)
    tokens_count: Optional[int] = Field(default=None, nullable=True)
    error_code: Optional[str] = Field(default=None, max_length=128)
    correlation_id: Optional[str] = Field(default=None, max_length=255, index=True)
    created_at: datetime = Field(default_factory=utcnow, nullable=False)
    updated_at: datetime = Field(default_factory=utcnow, nullable=False)


class MessageAttachment(SQLModel, table=True):
    __tablename__ = "message_attachments"

    id: UUID = Field(default_factory=uuid4, primary_key=True, index=True)
    message_id: UUID = Field(foreign_key="messages.id", nullable=False, index=True)
    filename: str = Field(max_length=255, nullable=False)
    content_type: str = Field(max_length=255, nullable=False)
    data: Optional[bytes] = Field(default=None, sa_column=Column(LargeBinary, nullable=True))
    storage_filename: Optional[str] = Field(default=None, max_length=255, nullable=True)
    size_bytes: Optional[int] = Field(default=None, nullable=True)
    created_at: datetime = Field(default_factory=utcnow, nullable=False)


class ProviderThreadState(SQLModel, table=True):
    """Per-thread provider state persisted for external LLM services."""

    __tablename__ = "provider_thread_states"
    __table_args__ = (UniqueConstraint("thread_id", "provider", name="uq_provider_thread"),)

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    thread_id: UUID = Field(foreign_key="threads.id", nullable=False, index=True)
    provider: str = Field(default="openai-compatible", max_length=64, nullable=False, index=True)
    conversation_id: Optional[str] = Field(default=None, max_length=255)
    payload: dict = Field(
        default_factory=dict,
        sa_column=Column(JSON, nullable=False, server_default="{}"),
    )
    created_at: datetime = Field(default_factory=utcnow, nullable=False)
    updated_at: datetime = Field(default_factory=utcnow, nullable=False)
